flask/login_sample/flaskr/models.py
from flaskr import db, login_manager
from flask_bcrypt import generate_password_hash, check_password_hash
from flask_login import UserMixin

# セッションに保存されたログインユーザーを返す
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


# UserMixinはflask-login
class User(UserMixin, db.Model):

    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), index=True)
    password = db.Column(db.String(128))

    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        self.password = generate_password_hash(password) # bcryptでハッシュ化

    def validate_passowrd(self, password):
        return check_password_hash(self.password, password)
    
    def add_user(self):
        with db.session.begin(subtransactions=True):
            db.session.add(self)
        db.session.commit()
    
    @classmethod
    def select_by_email(cls, email):
        return cls.query.filter_by(email=email).first()

flask/login_sample/flaskr/forms.py
from wtforms.form import Form
from wtforms.fields import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from flaskr.models import User


class LoginForm(Form):
    email = StringField('メール: ', validators=[DataRequired(), Email()])
    password = PasswordField('パスワード: ', validators=[DataRequired()])
    submit = SubmitField('ログイン')

class RegisterForm(Form):
    email = StringField('メール: ', validators=[DataRequired(), Email()])
    username = StringField('名前: ', validators=[DataRequired()])
    password = PasswordField(
        'パスワード: ', validators=[DataRequired(), EqualTo('password_confirm', message='パスワードが一致しまっせん')]
        )
    password_confirm = PasswordField('パスワード確認: ', validators=[DataRequired()])
    submit = SubmitField('登録')

    def validate_email(self, field):
        if User.select_by_email(field.data):
            raise ValidationError('メールアドレスはすでに登録されています。')

flask/login_sample/flaskr/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

login_manager = LoginManager()
login_manager.login_view = 'app.login'
login_manager.login_message = 'ログインしてください' # redirect時


basedir = os.path.abspath(os.path.dirname(__name__))
db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'mysite'
    app.config['SQLALCHEMY_DATABASE_URI'] =\
        'sqlite:///' + os.path.join(basedir, 'data.sqlite')
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    from flaskr.views import bp
    app.register_blueprint(bp)
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    return app

flask/login_sample/flaskr/views.py
from flask import Blueprint, request, render_template, redirect, url_for
from flask_login import login_user, login_required, logout_user
from flaskr.forms import LoginForm, RegisterForm
from flaskr.models import User


bp = Blueprint('app', __name__, url_prefix='/')

@bp.route('/')
def home():
    return render_template('home.html')

# ログインしていないと実行されない(login_userが実行される必要がある)
@bp.route('/welcome')
@login_required
def welcome():
    return render_template('welcome.html')

@bp.route('/logout')
@login_required
def logout():
    logout_user() # ログアウト
    return redirect(url_for('app.home'))

@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.select_by_email(form.email.data)
        if user and user.validate_passowrd(form.password.data):
            login_user(user)
            next = request.args.get('next') # 次のURL
            if not next:
                next = url_for('app.welcome')
            return redirect(next)
    return render_template('login.html', form=form)

@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User(
            email = form.email.data,
            username = form.username.data,
            password = form.password.data
        )
        user.add_user()
        return redirect(url_for('app.login'))
    return render_template('register.html', form=form)

@bp.route('/user')
@login_required
def user():
    return render_template('user.html')

flask/login_sample/flaskr/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>{{field.label }}
    <dd>{{ field(**kwargs)| safe }}
        {% if field.errors %}
        <ul class="errors">
            {% for error in field.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </dd>
</dt>
{% endmacro %}

flask/login_sample/flaskr/templates/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
    <ul class="nav">
        <li><a href="{{ url_for('app.home')}}">ホーム</a></li>
        {% if current_user.is_authenticated %}
        <li><a href="{{ url_for('app.logout') }}">ログアウト</a></li>
        {% else %}
        <li><a href="{{ url_for('app.login') }}">ログイン</a></li>
        <li><a href="{{ url_for('app.register') }}">登録</a></li>
        {% endif %}
        <li><a href="{{ url_for('app.user') }}">ユーザー画面</a></li>
    </ul>
    {% block content %}
    {% endblock %}
    </body>
</html>

flask/login_sample/flaskr/templates/home.html
{% extends "base.html" %}
{% block content %}
    <div>
        {% if current_user.is_authenticated %}
        <p>ユーザーログイン済み{{current_user.username}}</p>
        {% else %}
        <p>ログイン or 登録をしてください</p>
        {% endif %}
    </div>
{% endblock %}

flask/login_sample/flaskr/templates/login.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block content %}
{% for message in get_flashed_messages() %} {# リダイレクトした際のメッセージ #}
{{ message }}
{% endfor %}
<form method="POST">
    {{form.csrf_token}}
    {{render_field(form.email)}}
    {{render_field(form.password)}}
    {{form.submit()}}
</form>
{% endblock %}

flask/login_sample/flaskr/templates/register.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block content %}
<h1>ユーザー情報登録画面</h1>
<form method="POST">
    {{form.csrf_token}}
    {{render_field(form.username)}}
    {{render_field(form.email)}}
    {{render_field(form.password)}}
    {{render_field(form.password_confirm)}}
    {{form.submit()}}
</form>
{% endblock %}

flask/login_sample/flaskr/templates/user.html
{% extends "base.html" %}
{% block content %}
<h1>ユーザー画面</h1>
{% endblock %}

flask/login_sample/flaskr/templates/welcome.html
{% extends "base.html" %}
{% block content %}
<h1>ログイン完了しました</h1>
{% endblock %}