flask/sns_application/flaskr/views.py
from datetime import datetime
from flask import (
    Blueprint, abort, request, render_template,
    redirect, url_for, flash, session
)
from flask_login import login_user, login_required, logout_user, current_user
from flaskr.models import (
    User, PasswordResetToken
)
from flaskr import db
from flaskr.forms import (
    LoginForm, RegisterForm, ResetPassowrdForm, ForgotPasswordForm, 
    UserForm, ChangePasswordForm, UserSearchForm, ConnectForm
)

bp = Blueprint('app', __name__, url_prefix='')

@bp.route('/')
def home():
    return render_template('home.html')

@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('app.home'))

@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.select_user_by_email(form.email.data)
        if user and user.is_activate and user.validate_password(form.password.data):
            login_user(user, remember=True)
            next = request.args.get('next')
            if not next:
                next = url_for('app.home')
            return redirect(next)
        
        elif not user:
            flash('存在しないユーザーです')
        
        elif not user.is_activate:
            flash('無効なユーザーです。パスワードを再設定してください')
        
        elif not user.validate_password(form.password.data):
            flash('メールアドレスとパスワードの組み合わせが誤っています')
    return render_template('login.html', form=form)

@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User(
            username = form.username.data,
            email = form.email.data
        )
        with db.session.begin(subtransactions=True):
            user.create_new_user()
        db.session.commit()
        token = ''
        with db.session.begin(subtransactions=True):
            token = PasswordResetToken.publich_token(user)
        db.session.commit()
        # 本来はメールが良い
        print(
            f'パスワード設定用URL: http://127.0.0.1:5000/reset_password/{token}'
        )
        flash('パスワード設定用のURLをお送りしました。ご確認ください。')
        return redirect(url_for('app.login'))
    return render_template('register.html', form=form)

@bp.route('/reset_password/<uuid:token>', methods=['GET', 'POST'])
def reset_password(token):
    form = ResetPassowrdForm(request.form)
    reset_user_id = PasswordResetToken.get_user_id_by_token(token)
    if not reset_user_id:
        abort(500)
    if request.method == 'POST' and form.validate():
        password = form.password.data
        user = User.select_user_by_id(reset_user_id)
        with db.session.begin(subtransactions=True):
            user.save_new_password(password)
            PasswordResetToken.delete_token(token)
        db.session.commit()
        flash('パスワードを更新しました')
        return redirect(url_for('app.login'))
    return render_template('reset_password.html', form=form)

@bp.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    form = ForgotPasswordForm(request.form)
    if request.method == 'POST' and form.validate():
        email = form.email.data
        user = User.select_user_by_email(email)
        if user:
            with db.session.begin(subtransactions=True):
                token = PasswordResetToken.publich_token(user)
            db.session.commit()
            reset_url = f'http://127.0.0.1:5000/reset_password/{token}'
            print(reset_url)
            flash('パスワード再設定用のURLを発行しました')
        else:
            flash('存在しないユーザーです')
    return render_template('forgot_password.html', form=form)

@bp.route('/user', methods=['GET', 'POST'])
@login_required
def user():
    form = UserForm(request.form)
    if request.method == 'POST' and form.validate():
        user_id = current_user.get_id()
        user = User.select_user_by_id(user_id)
        with db.session.begin(subtransactions=True):
            user.username = form.username.data
            user.email = form.email.data
            file = request.files[form.picture_path.name].read()
            if file:
                file_name = user_id + '_' + \
                    str(int(datetime.now().timestamp())) + '.jpg'
                picture_path = 'flaskr/static/user_image/' + file_name
                open(picture_path, 'wb').write(file)
                user.picture_path = 'user_image/' + file_name
        db.session.commit()
        flash('ユーザー情報の更新に成功しました')
    return render_template('user.html', form=form)

@bp.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.select_user_by_id(current_user.get_id())
        password = form.password.data
        with db.session.begin(subtransactions=True):
            user.save_new_password(password)
        db.session.commit()
        flash('パスワードの更新に成功しました')
        return redirect(url_for('app.user'))
    return render_template('change_password.html', form=form)

@bp.route('/user_search', methods=['GET', 'POST'])
@login_required
def user_search():
    form = UserSearchForm(request.form)
    connect_form = ConnectForm()
    session['url'] = 'app.user_search'
    users = None
    if request.method == 'POST' and form.validate():
        username = form.username.data
        users = User.search_by_name(username)
        
    return render_template(
        'user_search.html', form=form, connect_form=connect_form, users=users
        )

@bp.app_errorhandler(404)
def page_not_found(e):
    return redirect(url_for('app.home'))

@bp.app_errorhandler(500)
def server_error(e):
    return render_template('500.html'), 500

flask/sns_application/flaskr/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>
    {{ field.label }}
    <dd>
        {{ field(**kwargs)| safe}}
        {% if field.errors %}
        <ul class="errors">
            {% for error in field.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </dd>
</dt>
{% endmacro %}

flask/sns_application/flaskr/templates/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}FLASK SNS{% endblock %}</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{url_for('app.home')}}">
                ホーム
            </a>
            {% if current_user.is_authenticated %}
            <a class="navbar-brand" href="{{url_for('app.logout')}}">
                ログアウト
            </a>
            <a class="navbar-brand" href="{{ url_for('app.user') }}">
                ユーザー情報編集
            </a>
            <a class="navbar-brand" href="{{url_for('app.user_search')}}">
                ユーザー検索
            </a>
            {% else %}
            <a class="navbar-brand" href="{{url_for('app.login')}}">
                ログイン
            </a>
            <a class="navbar-brand" href="{{url_for('app.register')}}">
                登録
            </a>
            {% endif %}
        </nav>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

flask/sns_application/flaskr/templates/change_password.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
パスワード変更画面 - {{ super() }}
{% endblock %}
{% block content %}
<h1>パスワード変更画面</h1>
<div class="row">
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.password) }}
        {{ render_field(form.confirm_password) }}
        {{ form.submit() }}
    </form>
</div>
{% endblock %}

flask/sns_application/flaskr/templates/forgot_password.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
パスワード再発行 - {{ super() }}
{% endblock %}
{% block content %}
{% for message in get_flashed_messages() %}
{{ message }}
{% endfor %}
<h1>パスワード再発行画面</h1>
<div class="row">
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.email) }}
        {{ form.submit() }}
    </form>
</div>
{% endblock %}

flask/sns_application/flaskr/templates/home.html
{% extends "base.html" %}
{% block title %}
ホーム- {{ super() }}
{% endblock %}
{% block content %}
<div class="row">
    {% if current_user.is_authenticated %}
    <div class="col-lg-2 offset-lg-2">
        {% if current_user.picture_path %}
            <img class="user-image-big" src="{{ url_for('static', filename=current_user.picture_path)}}">
        {% endif %}
    </div>
    <div class="col-lg-4 offset-lg-2">
        <p>ユーザ名: {{ current_user.username }}</p>
        <p>メールアドレス: {{ current_user.email }}</p>
    </div>
    {% else %}
        <p>ログイン or 登録をしてください</p>
    {% endif %}
</div>
{% endblock %}

flask/sns_application/flaskr/templates/login.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ログイン - {{ super() }}
{% endblock %}
{% block content %}
{% for message in get_flashed_messages() %}
{{ message }}
{% endfor %}
<div class="row">
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.email) }}
        {{ render_field(form.password) }}
        {{ render_field(form.confirm_password) }}
        {{ form.submit() }}
    </form>
    <a href="{{url_for('app.forgot_password')}}">
        パスワードを忘れた場合
    </a>
</div>
{% endblock %}

flask/sns_application/flaskr/templates/register.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ユーザー登録 - {{ super() }}
{% endblock %}
{% block content %}
<h1>ユーザー情報登録画面</h1>
<div class="row">
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.username) }}
        {{ render_field(form.email) }}
        {{ form.submit() }}
    </form>
</div>
{% endblock %}

flask/sns_application/flaskr/templates/reset_password.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
パスワード登録 - {{ super() }}
{% endblock %}
{% block content %}
<h1>パスワード登録画面</h1>
<div class="row">
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.password) }}
        {{ render_field(form.confirm_password) }}
        {{ form.submit() }}
    </form>
</div>
{% endblock %}

flask/sns_application/flaskr/templates/user.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ユーザー情報編集画面 - {{ super() }}
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-lg-8 offset-lg-4">
    {% for message in get_flashed_messages() %}
    {{ message }}
    {% endfor %}
    </div>
    <div class="col-lg-2 offset-lg-2">
        {% if current_user.picture_path %}
        <img class="user-image-big" src="{{ url_for('static', filename=current_user.picture_path)}}">
        {% endif %}
    </div>
    <div class="col-lg-4 offset-lg-2">
        <form method="POST" enctype="multipart/form-data">
            {{ form.csrf_token }}
            {{ render_field(form.username, value=current_user.username)}}
            {{ render_field(form.email, value=current_user.email)}}
            {{ render_field(form.picture_path)}}
            {{ form.submit()}}
        </form>
        <a href="{{url_for('app.change_password')}}">パスワードを変更する</a>
    </div>
</div>
{% endblock %}

flask/sns_application/flaskr/templates/user_search.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ユーザー検索 - {{ super() }}
{% endblock %}
{% block content %}
<div class="jumbotron">
    <p>ユーザー検索画面</p>
</div>
<div class="row">
    <div class="col-lg-12">
        <form method="POST">
            {{form.csrf_token}}
            {{render_field(form.username)}}
            {{form.submit()}}
        </form>
    </div>
    <div class="col-lg-12">
        {% if users %}
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>ユーザー画像</th>
                    <th>ユーザー名</th>
                    <th>申請ボタン</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <th>{{ loop.index }}</th>
                    {% if user.picture_path %}
                    <th>
                        <img class="user-image-small" src="{{url_for('static', filename=user.picture_path)}}">
                    </th>
                    {% else %}
                    <th></th>
                    {% endif %}
                    <th>{{ user.username }}</th>
                    <th>
                        {% if user.joined_status_from_to == 2 or user.joined_status_to_from == 2 %}
                        友達
                        {% elif user.joined_status_from_to == 1 %}
                        友達申請中
                        {% elif user.joined_status_to_from == 1 %}
                        <form method="POST" action="{{ url_for('app.connect_user')}">
                            {{ connect_form.csrf_token}}
                            {{ connect_form.connect_condition(value='accept')}}
                            {{ connect_form.to_user_id(value=user.id)}}
                            {{ connect_form.submit(class='btn btn-primary', value='友達申請承認')}}
                        </form>
                        {% else %}
                        <form method="POST" action="{{url_for('app.connect_user')}}">
                            {{ connect_form.csrf_token}}
                            {{ connect_form.connect_condition(value='connect')}}
                            {{ connect_form.to_user_id(value=user.id)}}
                            {{ connect_form.submit(class='btn btn-primary', value='友達申請する')}}
                        </form>
                        {% endif %}
                    </th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}